---
title: "Glucose by Menstrual Cycle Phase"
format: html
---

```{r setup}
library(duckdb)
library(DBI)
library(ggplot2)


knitr::opts_knit$set(root.dir = here::here())
con <- dbConnect(duckdb())
```

```{sql, connection=con, output.var="daily_glucose"}
SELECT gluc.id, gluc.day_in_study, hormone.phase,
       AVG(gluc.glucose_value) AS avg_glucose,
       STDDEV(gluc.glucose_value) AS stdev_glucose,
       COUNT(*) as n_readings
FROM read_csv_auto('data/raw/glucose.csv') AS gluc
JOIN read_csv_auto('data/raw/hormones_and_selfreport.csv') AS hormone
  ON gluc.id = hormone.id 
 AND gluc.day_in_study = hormone.day_in_study
WHERE hormone.phase IS NOT NULL
  AND gluc.id NOT IN (6, 11)
GROUP BY gluc.id, gluc.day_in_study, hormone.phase
HAVING COUNT(*) >= 276
ORDER BY gluc.id, gluc.day_in_study
```

```{r plot}
ggplot(daily_glucose, aes(x = phase, y = avg_glucose)) +
  geom_boxplot() + theme_minimal()+
  labs(title = "Daily mean glucose by cycle phase",
       x = "Phase", 
       y = "Mean glucose (mmol/L)")
```